### ISSUE TITLE
Virtual Text problem

### ISSUE THREAD

**Issue by fedoranvar** [pyrho/nerveux.nvim#3]
Good day to you!

I have a problem with `virtual_title=true`:
When in normal mode, it leaves one left square brace and some empty space at right,
![image](https://user-images.githubusercontent.com/52028706/135952635-dd29f0cc-22f1-4603-aa4d-eeb2a6ae901f.png)

in insert mode it shows raw text with virtual at then end of the line
![image](https://user-images.githubusercontent.com/52028706/135952791-85b7a467-44b1-4db5-801b-10bd11b8b023.png)

How it can be fixed?

Thank you!

**Comment by fedoranvar** [comment]
hmm, i figured something

1) brackets works fine if link not in the beggining on the line (minimal 1 space from the 0 column)
![image](https://user-images.githubusercontent.com/52028706/135953523-0c2f7b36-6965-461e-b096-9f1cc3653293.png)
2) Extra space is for markdown-filename of link

**Comment by pyrho** [comment]
Hey there sorry for the late response.

Yes this is a known bug, from what I recall it seems to be an issue with how neovim handles virtual text; I have not had time to properly investigate the issue in neovim's code and submit a proper bug report.

It's something I've learned to live with :)

edit: on neovim 0.6-ga6cdfa27d and before it seems like virtual text cannot start from the first column. It simply won't show, that's why I hacked it this was and artificially shifted the virtual text to start at the second column.
